# Generated by Django 2.1.4 on 2020-01-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbprojekte',
            name='projCreated',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
