# Generated by Django 2.1.4 on 2020-01-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20200118_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.CharField(max_length=60)),
                ('compTotal', models.SmallIntegerField()),
                ('compDesc', models.CharField(max_length=60)),
                ('compPackage', models.CharField(max_length=20)),
                ('compDist', models.CharField(max_length=20)),
                ('compPartNum', models.CharField(max_length=40)),
            ],
        ),
    ]
