# Generated by Django 2.1.4 on 2020-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_tbtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbUnitTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=60)),
                ('testDesc', models.CharField(max_length=60)),
                ('testUnit', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='tbTest',
        ),
    ]
